### ISSUE TITLE
Stopped after filling the fourth form 

### ISSUE THREAD

**Issue by nishant19** [rajujha373/moodle_feedback_filler#2]
Mine stopped after filling the fourth form  .
Let me know, if it worked fine in your system .

**Comment by irkartik** [comment]
Would you please clarify after filling of which subject's feedback the script abruptly stopped?
I suggest you to use the fresh codes from the repo as the problem you are facing has been solved already as per my knowledge. 
P.S. the code worked fine for me on my system

**Comment by nishant19** [comment]
OS specific issue then, i guess . Because it was unable to install all the requirements in the .txt file.
Take care of your mac audience then, in some later future, 😜

Awesome work with selenium, though bro. Was looking to use it for some time now

**Comment by irkartik** [comment]
Requirements.txt file consisted of just some basic tools required to run the script on user's pc, if that libraries didn't get installed it would have caused you error at the time of starting. The error you have mentioned looks like a runtime exception. 
It would be great if you can share your code with us. Will definitely try to debug youur issue :)
Also, share the screenshot of the error log. That would be of great help. Thank you
